bcm_vc_cma: create_proc_entry replaced by proc_create
Commit 80e928f7 kills create_proc_entry, so need to get rid if it and replace by proc_create

drivers/char/broadcom/vc_cma/vc_cma.c: In function 'vc_cma_init':
drivers/char/broadcom/vc_cma/vc_cma.c:1088:2: error: implicit declaration of function 'create_proc_entry' [-Werror=implicit-function-declaration]
drivers/char/broadcom/vc_cma/vc_cma.c:1088:20: error: assignment makes pointer from integer without a cast [-Werror]
drivers/char/broadcom/vc_cma/vc_cma.c:1095:19: error: dereferencing pointer to incomplete type
drivers/char/broadcom/vc_cma/vc_cma.c: In function 'vc_cma_exit':
drivers/char/broadcom/vc_cma/vc_cma.c:1134:38: error: dereferencing pointer to incomplete type
cc1: all warnings being treated as errors
distcc[13074] ERROR: compile drivers/char/broadcom/vc_cma/vc_cma.c on localhost failed
make[4]: *** [drivers/char/broadcom/vc_cma/vc_cma.o] Error 1
make[3]: *** [drivers/char/broadcom/vc_cma] Error 2
make[2]: *** [drivers/char/broadcom] Error 2
make[1]: *** [drivers/char] Error 2
make: *** [drivers] Error 2